name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Setup JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Setup Ninja
      uses: lukka/get-cmake@latest

    - name: Write key
        if: github.event_name != 'pull_request'
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: ${{ github.sha }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
